const PATHS = {
    welcome1: require('../../../assets/images/welcome/welcome1.png'),
    welcome2: require('../../../assets/images/welcome/welcome2.png'),
    welcome3: require('../../../assets/images/welcome/welcome3.png'),
    signIn: require('../../../assets/images/signin.png'),
    signUp: require('../../../assets/images/signup.png'),
    winners: require('../../../assets/images/winners.png'),
    cup: require('../../../assets/images/cup.png'),
    phone: require('../../../assets/images/phone.png'),
    bike: require('../../../assets/images/bike.png'),
    promotion: require('../../../assets/images/promotion.png'),
    cashPoints: require('../../../assets/images/cashPoints.png'),
    logo: require('../../../assets/images/logo.png'),
    foodcup: require('../../../assets/images/foodcup.png'),
    food: require('../../../assets/images/food.png'),
    forget: require('../../../assets/images/forget.png'),
    celebration: require('../../../assets/images/celebration.png'),
    ordering: require('../../../assets/images/settings/ordering.jpg'),
    payment: require('../../../assets/images/settings/payment.png'),
    delivery: require('../../../assets/images/settings/delivery.jpg'),
    feedback: require('../../../assets/images/settings/feedback.jpg'),
    promotions: require('../../../assets/images/settings/promotions.png'),
    contact: require('../../../assets/images/settings/contact.jpg'),
}

export default PATHS;